### ISSUE TITLE
Feature list WebdriverJS v2.0.0

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#188]
This is the list of the upcoming WebdriverJS features which will be implemented with v2.0.0. Feel free to add missing features! If a checkbox is checked the feature is already implemented within [v2.0.0](https://github.com/camme/webdriverjs/tree/v2.0.0) branch, so you get an idea of the current status of progress.
- [x] **return command result**<br>(see #133) currently not all commands return the actual value of the JSONWire command. Some are just returning the response payload. This should be handled consistently. Therefor the callback will return in the following way: 1st parameters is the error object, 2nd parameter will be the actual value of the command and the 3rd parameter returns the whole response payload.
- [x] **format command result**<br>all commands should return its values in a formatted way. This makes it easier to test the results. E.g. if you try to get the style attribute of the following element:

``` html
<div id="elem" style="position: absolute, top: 50%, background-color: yellow">content</div>
```

you'll get the following result of type string:

```
position:absolute,top:50%,background-color:yellow
```

This is how it should be:

``` js
{
    position: 'absolute',
    top: {
        type: 'number',
        string: '5%',
        unit: '%',
        value: 5
    },
    backgroundColor: 'yellow'
}
```
- [x] **break tests if commands fail**<br>if a command fails it should throw an assertion error and break the test. Currently it doesn't if no callback is given. Because of this many tests look like this:

``` js
var noError = function(err,res) {
    assert(err, 'error occured');
};

...

it('should delete cookie', function(done) {
    client
        .deleteCookie('someCookie', noError)
        .call(done);
}
```
- [x] **add missing JSONWire protocol commands**<br>implement the following missing commands:<br>
  /session/:sessionId/frame/parent ✓
  /session/:sessionId/location ✓
  /session/:sessionId/local_storage ✓
  /session/:sessionId/local_storage/key/:key ✓
  /session/:sessionId/local_storage/size ✓
  /session/:sessionId/session_storage ✓
  /session/:sessionId/session_storage/key/:key ✓
  /session/:sessionId/session_storage/size ✓
  /session/:sessionId/log ✓
  /session/:sessionId/log/types ✓
  /session/:sessionId/application_cache/status ✓
  /session/:sessionId/element/active ✓
  /session/:sessionId/context ✓ (Appium specific protocol command)
- [x] **truncate screenshot in command result**<br>(see #183)
- [x] **improve tests**<br>some tests are currently pretty unstable and fail sometimes although they should work. Therefor each command should be tested separately. That means that each command gets a simple test page and will be tested in an own spec file. All commands should get tested to ensure a high test coverage.
- [x] **generate docs**<br>to keep the maintenance of the [Webdriver.io](http://webdriver.io) website as simple as possible we should generate some content parts (especially the command documentation). Therefor a mechanism should be implemented that generates the yaml files for the website out of the command describing comments of all protocol and action commands - [role model here is the angularjs project](http://youtu.be/5mHjJ4xf_K0?t=2m20s)
- [x] **provide command to take screenshot of full document height/width**<br>(see #191)
- [x] **enable actions on multiple elements**<br>if given selector finds more then one element the action should be executed on all these elements. Therefor the response should return an array of results
- [x] **implement waitForCondition commands**<br>(see #202, #201) a waitForCondition takes a script, continues to run it until the condition is met. With the help of executeAsync, this is easily achievable. waitForCondition will enable a new range of powerful capabilities with regard to dom elements, and it would be great to support them of the box:

``` js
/* ✓ */ - waitForVisible(element, reverse /* set to true for invisible*/, timeout, callback(err))
/* ✓ */ - waitForExist(element, reverse /* set to true for missing*/, timeout, callback(err))
/* ✓ */ - waitForChecked(element, reverse /* set to true for unchecked*/, timeout, callback(err))
/* ✓ */ - waitForSelected(element, reverse /* set to true for unselected*/, timeout, callback(err))
/* ✓ */ - waitForEnabled(element, reverse /* set to true for disabled*/, timeout, callback(err))
/* ✓ */ - waitForText(element, text, timeout, callback(err))
/* ✓ */ - waitForValue(formElement, value, timeout, callback(err))
```
- [x] added support for Appium specific protocol commands
  backgroundApp ✓
  closeApp ✓
  complexFindInApp ✓
  deviceKeyEvent ✓
  endTestCoverageForApp ✓
  getAppStrings ✓
  getCurrentDeviceActivity ✓
  getNetworkConnection ✓
  hideDeviceKeyboard ✓
  installAppOnDevice ✓
  isAppInstalledOnDevice ✓
  launchApp ✓
  lock ✓
  openNotifications ✓
  performMultiAction ✓
  performTouchAction ✓
  pullFileFromDevice ✓
  pushFileToDevice ✓
  removeAppFromDevice ✓
  resetApp ✓
  rotate ✓
  setImmediateValueInApp ✓
  setNetworkConnection ✓
  shake ✓
  toggleAirplaneModeOnDevice ✓
  toggleDataOnDevice ✓
  toggleLocationServicesOnDevice ✓
  toggleWiFiOnDevice ✓
- [x] _may get extended during development_
