### ISSUE TITLE
[💡 Feature]: ESM Compatibility

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#8306]
### Is your feature request related to a problem?

Our goal for v8 is to deliver WebdriverIO packages for more than just Node.js environments. As a first step, let's make WebdriverIO ESM compatible (for that see `v8` branch). Next is to make all community packages compatible by moving them to ESM otherwise they can't be used in v8. The packages owned by this community are tracked here:

- [ ] webdriverio-community/wdio-vscode-service#21
- [ ] webdriverio-community/wdio-intercept-service#310
- [ ] webdriverio-community/wdio-geckodriver-service#33
- [ ] webdriverio-community/wdio-safaridriver-service#6
- [ ] webdriverio-community/wdio-electron-service#35
- [ ] webdriverio-community/wdio-rerun-service#36
- [ ] webdriverio-community/wdio-chromedriver-service#78
- [ ] webdriverio-community/wdio-teamcity-reporter#31
- [ ] webdriverio-community/wdio-video-reporter#74
- [ ] webdriverio-community/wdio-cucumberjs-json-reporter#96
- [ ] webdriverio-community/wdio-edgedriver-service#5
- [ ] webdriverio/selenium-standalone#678
- [ ] webdriverio/wdio-wait-for#160

### Describe the solution you'd like.

Make sure that all packages are exported and published in way to be used using CJS and ESM.

### ‼️ Attention ‼️

Anyone who likes us to support in this effort, just pick one of the packages above and help transform them into ESM. You can follow [this example commit](https://github.com/webdriverio/webdriverio/commit/99ad90f244498409f07bfff9fdbdce7598fcab3f) to get a sense of what needs to be changed. Also this: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c is a good resource.

### Updates

- 2022/07/05: ~it seems that the best tool to compile a hybrid modules is [`unbuild`](https://www.npmjs.com/package/unbuild), I am currently adding this build step to the [`v8`](https://github.com/webdriverio/webdriverio/commit/ac071f92cb32341cab9f65db239127d2d1ce0ecd) branch - the only problem is what to do with modules that only support ESM~
- 2022/07/07: it turns out that there is absolutely no need to transpile WebdriverIO packages into CJS. When using the testrunner we can dynamically import the cli as ESM module and for the `webdriverio`, `webdriver` and `devtools` packages we can just provide a CJS shim and import the ESM version too.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by christian-bromann** [comment]
With https://github.com/webdriverio/webdriverio/commit/e970be91d016d9c8ed69e7837ddb5b6e96c108a4 we finalised the ESM transition of the core modules. It is not required for services and reporters to transition to ESM before the `v8` release. Therefor we can close this and mark it as done 🎉
