### ISSUE TITLE
[🏡 Internal]: Browser Runner Task List

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#9126]
In #9055 I have been implementing a new runner package for component testing in the browser. In order to properly test it in an actual repository I released it as alpha prematurely. This issue covers some tasks that need to be done for the actual release:

- [x] write documentation
- [x] update release blog post
- [x] fix outstanding bugs
- [x] specs path is relative to cwd not relative from `wdio.conf.ts`
- [x] add runner option to configuration wizard
- [x] allow setting vite config path rather than preset
- [x] fixe [this smoke test](https://github.com/webdriverio/webdriverio/pull/9055/commits/db12f53244d9b1c92684364e0bf3bee78d40621a)
- [x] [`query-selector-shadow-dom`](https://github.com/Georgegriff/query-selector-shadow-dom) is CJS and in order to test Lit components you want to allow it within ESM environment
- [x] component testing [example repo](https://github.com/webdriverio/component-testing-examples)
- [x] hook support
- [x] mention changes to config parse relative url
