### ISSUE TITLE
Rewrite Messaging between worker and testrunner

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/webdriverio#9299]
The WebdriverIO testrunner communicates via inter process calls (IPC) between the main testrunner process and the worker. All these IPC messages have almost no typing and often contain more information than needed. It's time to clean this up and make it more type strict.

**Comment by serhatozdursun** [comment]
Hello
I'd love to contribute to this issue and help improve the IPC messaging system by introducing stricter TypeScript types and cleaning up unnecessary payload data.

Before I start, I’d appreciate a bit of guidance on where to begin:

Which files or modules should I look into first for IPC message handling between the main testrunner and the worker?

Is there an existing structure or pattern I should follow for typing messages?

Any tips on areas that are especially prone to redundant or overly generic messages?

Once I get some direction, I’ll happily take it from there. Thanks for maintaining such a great project — looking forward to contributing!

Best,
Serhat

**Comment by serhatozdursun** [comment]
## 🧭 IPC Refactor Roadmap: WebdriverIO Testrunner ↔ Worker

This roadmap outlines the proposed steps to refactor IPC communication in WebdriverIO between the main testrunner and worker processes. The goal is to migrate from untyped `process.send`/`process.on` usage to a structured, type-safe RPC model using [birpc](https://www.npmjs.com/package/birpc).

---

### ✅ Goal

* Replace all `process.send`/`process.on('message')` calls with `birpc`.
* Centralize and type all IPC messages in `packages/wdio-types/src/Workers.ts`.
* Improve maintainability, testability, and future support (e.g., WebWorkers).

---

### 📌 Key Motivations

* Existing IPC is scattered and inconsistently typed.
* Manual mapping and casting via `process.send` is error-prone.
* Clear need for bidirectional, typed messaging (birpc fits perfectly).

---

### 🧱 Phase 1: Audit & Categorization

* [x] Identify all `process.send` calls in worker packages (✅ done)
* [x] Group messages by purpose (`snapshot`, `sessionEnded`, etc.)
* [x] Map messages to candidate function names for `birpc`
* [x] Confirm missing message types in `MESSAGE_TYPES`

---

### 📦 Phase 2: Type Normalization

* [ ] Add missing `MESSAGE_TYPES` enum values
* [ ] Extend `SocketMessageValue` to cover newly mapped messages
* [ ] Define common message payload types (e.g., `SnapshotResult`, `DebugResult`)

---

### 🛠️ Phase 3: birpc Migration (Worker → Runner)

* [ ] Introduce `ServerFunctions` interface in `@wdio/types`
* [ ] Replace `process.send({...})` with `rpc.<method>()`
* [ ] Create `createRpcChannel()` abstraction for portability

---

### 🔁 Phase 4: Runner Receivers

* [ ] Replace `process.on('message')` with `birpc` receiver
* [ ] Implement actual `ServerFunctions` handlers in runner context
* [ ] Ensure correct error handling and async support

---

### 🧪 Phase 5: Testing & Backward Compatibility

* [ ] Add unit tests for both RPC sender and receiver paths
* [ ] Ensure legacy paths are either removed or feature-flagged

---

### 🔮 Phase 6 (Optional): Worker Strategy Abstraction

* [ ] Assess replacing `child_process.fork()` with WebWorkers or threads
* [ ] Use `birpc` protocol-agnostic support for easy swapping

---

### 📁 Proposed Interfaces (`ServerFunctions`)

```ts
interface ServerFunctions {
  snapshot(data: SnapshotResult): void
  sessionEnded(cid: string): void
  ready(): void
  printFailureMessage(content: any): void
  reporterRealTime(content: any): void
  workerEvent(event: Workers.WorkerEvent): void
  startDebugger(params: { commandTimeout: number; introMessage: string }): void
  debuggerResult(params: { result?: any; error?: any }): void
  error(content: { name: string; message: string; stack?: string }): void
}
```

---

### 📎 Files Affected

* `packages/wdio-runner/src/index.ts`
* `packages/wdio-runner/src/browser.ts`
* `packages/wdio-runner/src/reporter.ts`
* `packages/wdio-local-runner/src/run.ts`
* `packages/webdriverio/src/commands/browser/debug.ts`
* `packages/wdio-utils/src/monad.ts`
* `packages/wdio-utils/src/test-framework/errorHandler.ts`
* `packages/wdio-types/src/Workers.ts`

---

### 📣 Request for Feedback

* Does this direction align with the long-term architecture vision?
* Should we adopt `zod` or another validator for message payloads?
* Should legacy `process.send` support remain during migration?

**Comment by christian-bromann** [comment]
> Phase 2: Type Normalization

Let's make sure we separate the message types for browser runner and local runner. To clarify here: the local runner orchestrates WDIO workers (currently separate processes but happy to use WebWorkers). The messages handled by the local runner are related to the worker lifecycle and apply to all types of testrunner tests (including using the browser runner)

The browser runner on the other side introduces additional messages that is needed to enable communication between the browser environment (when running component tests) and the worker. The browser runner initiates a Vite server as part of the main testrunner process. That Vite server manages a socket connection to the browser which we use to propagate command request/responses and other type of messages to the WebdriverIO instance managed by the WDIO worker. Basically the message chain goes as following:

<img width="1271" alt="Image" src="https://github.com/user-attachments/assets/aee8c26f-b1e9-499e-a49c-f291e2fcae63" />

> * Assess replacing `child_process.fork()` with WebWorkers or threads

That would be amazing if we could do this as part of this effort. It seems a low hanging fruit with a lot of value.

> * Does this direction align with the long-term architecture vision?

Absolutely. This part has been neglected for a while and I would love to see improvements in this area.

> * Should we adopt `zod` or another validator for message payloads?

💯 Happy to introduce Zod here. Though message passing here is all internal so there is no real need to validate them. Maybe to keep the scope small, we define messages as TypeScript types only and evaluate later to migrate to Zod?

> * Should legacy `process.send` support remain during migration?

Not if we migrate to WebWorkers.

**Comment by christian-bromann** [comment]
Thanks for the update, looking forward to the result here.

**Comment by serhatozdursun** [comment]
## Help Needed with `feat/ipc-type-safety` Branch

Hi @christian-bromann ,

I've been working on the [`feat/ipc-type-safety`](https://github.com/serhatozdursun/webdriverio/tree/feat/ipc-type-safety) branch in the WebdriverIO repo. Right now, I'm feeling a bit stuck with the `birpc` implementation.

If the IPC typing part (introduced via `IPC_MESSAGE_TYPES` and `IPCMessage<T>`) looks solid to you, I'm considering rolling back the `wdio-rpc` package for now. We could treat the `birpc` integration as a separate step after finalizing the types.

Would appreciate your thoughts or feedback on this direction.

Thanks!

**Comment by christian-bromann** [comment]
> I’ve created a new internal package: [`wdio-rpc`](https://github.com/serhatozdursun/webdriverio/tree/feat/ipc-type-safety/packages/wdio-rpc), where I started implementing the `birpc` layer.

I like the idea to put all logic for sending messages between worker and main process into a single package. Nice job! 👍  It would be great if we could hide this part:

```ts
        (msg) => process.send?.(msg),
        (fn) => process.on('message', fn))
```

in the consumer packages. For now we can hard code it into `@wdio/rpc`, eventually we want to allow create different types of rpc instances, e.g.

```ts
// for RPC calls between process using e.g. `process.send`
createClientRpc<..., ...>('process', { ... })
// for message events in threads using e.g. `worker.postMessage`
createClientRpc<..., ...>('worker', { ... })
```

What do you think?

> I did my best here, but I’m not 100% confident — would appreciate a quick review to see if the approach looks correct.

I think it makes sense. Couldn't see an issue with this approach.

> This ended up being more time-consuming than I initially expected, and I think it would be more manageable to stabilize the type-safe structure first before layering in the new abstraction.

I will leave this up to you. Moving the messaging of workers into an extra package makes sense to me and I think makes it also easier to review. But I can totally understand if you like to take smaller steps and do the type changes first. That makes sense as well.

**Comment by serhatozdursun** [comment]
I’ve finally been able to raise the PR: https://github.com/webdriverio/webdriverio/pull/14544
There were a few issues with my Git settings, but everything should be resolved now.

As I mentioned earlier, I'm not entirely confident about the improvements I made — so I’d really appreciate a careful review. Please feel free to add any comments or suggestions that could help me refine the changes and get the PR ready for merge.

Thanks in advance! 🙏
